### ISSUE TITLE
README example installation instructions should use the https git url

### ISSUE THREAD

**Issue by andybak** [Picsart-AI-Research/LIVE-Layerwise-Image-Vectorization#2]
https://github.com/Picsart-AI-Research/LIVE-Layerwise-Image-Vectorization.git works for everyone. 

git@github.com:Picsart-AI-Research/LIVE-Layerwise-Image-Vectorization.git only works if you have the correct permissions.

**Comment by ma-xu** [comment]
@andybak Thanks for your kind suggestions. Updated.
