### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by andybak** [Picsart-AI-Research/LIVE-Layerwise-Image-Vectorization#3]
"LIVE is under the Apache-2.0 license. Please contact the authors for commercial use."

I might be misunderstanding something but if this is Apache 2.0 then you can't add further requirements such as restrictions on commercial use. That's how permissive licences work.

**Comment by ma-xu** [comment]
Thanks for your kind reminder. Wwe remove the restrictions in the readme file.
