### ISSUE TITLE
Dataset Evaluation

### ISSUE THREAD

**Issue by orhir** [Picsart-AI-Research/LIVE-Layerwise-Image-Vectorization#8]
Hi,

You describe a dataset in the paper called Pics used for evaluation.
Can you please share this dataset?

Thanks in advance.

**Comment by ma-xu** [comment]
@orhir Hi, this dataset is from Picsart and probably will not be publicly available. 
The dataset is just used for evaluation and our method requires no training data. Hence, you can evaluate on your own dataset if you want.
