### ISSUE TITLE
subprocess.CalledProcessError________returned non-zero exit status 1.

### ISSUE THREAD

**Issue by eleveneee** [Picsart-AI-Research/LIVE-Layerwise-Image-Vectorization#9]
First of all, thank you very much for your work!
I encountered the following issues during the process of configuring the environment for **Ubuntu and Windows**. I have collected a lot of information but it has not been resolved yet. What is the reason for this?
If you could answer, I would be very grateful!
The specific errors are as follows:

s**ubprocess.CalledProcessError**: Command '['cmake', 'D:\\Line Matching\\LIVE-Layerwise-Image-Vectorization-main\\DiffVG', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\\Line Matching\\LIVE-Layerwise-Image-Vectorization-main\\DiffVG\\build\\lib.win-amd64-cpython-37', '-DPYTHON_
INCLUDE_PATH=C:\\Anaconda\\envs\\live\\Include', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=D:\\Line Matching\\LIVE-Layerwise-Image-Vectorization-main\\DiffVG\\build\\lib.win-amd64-cpython-37', '-DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=D:\\Line Matching\\LIVE-Layerwi
se-Image-Vectorization-main\\DiffVG\\build\\lib.win-amd64-cpython-37', '-A', 'x64', '-DDIFFVG_CUDA=1']' **returned non-zero exit status 1**.

**Comment by jchapline07** [comment]
Hi I get the same error when trying to install 
would be great to get a fix

**Comment by ma-xu** [comment]
Thanks for your interest.

I didn't test Windows and probably will not try windows. Could you please post the error in Lunix and I can help.

**Comment by eleveneee** [comment]
> 
@ma-xu 
I encountered the same problem on Linux.

**Comment by ma-xu** [comment]
@eleveneee Could you please help post the error log?

**Comment by Inas-07** [comment]
I encountered the same issue on linux as well. Here's the error. 
```
CMake Error at /mnt/new/zhouyi/anaconda3/envs/live/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Python (missing: Python_INCLUDE_DIRS Python_LIBRARIES
  Development Development.Module Development.Embed) (Required is at least
  version "3.7")

subprocess.CalledProcessError: Command '['cmake', '/mnt/new/zhouyi/live/DiffVG', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/mnt/new/zhouyi/live/DiffVG/build/lib.linux-x86_64-cpython-37', '-DPYTHON_INCLUDE_PATH=/mnt/new/zhouyi/anaconda3/envs/live/include/python3.7m', '-DCMAKE_BUILD_TYPE=Release', '-DDIFFVG_CUDA=0']' returned non-zero exit status 1.
```

I've adhered to the setup instructions and had created a conda env with python 3.7. Seems that cmake couldn't find the python lib in anaconda.... not pretty sure though...

Still needs a fix

**Comment by ma-xu** [comment]
@Inas-07 Sorry that I have no idea about this error.

**Comment by Inas-07** [comment]
After some trial-and-error, here's my solution: navigate to DiffVG/CMakeLists.txt, find line 11, which is:
```
find_package(Python 3.7 COMPONENTS Development REQUIRED)
```
Replace it with 
```
find_package(Python 3.7 COMPONENTS REQUIRED)
```

**Comment by Inas-07** [comment]
After some trial-and-error I've found a potential solution (Although it would probably cause other issues, it works for me for now..)：
1. Navigate to DiffVG/CMakeLists.txt
2. Go to line 11, and remove the word `Development`, i.e. replace 
```
find_package(Python 3.7 COMPONENTS Development REQUIRED)
```
with 
```
find_package(Python 3.7 COMPONENTS REQUIRED)
``` 
Everything compiled just fine for me.

**Comment by ma-xu** [comment]
@Inas-07 Thank you very much for your help. Closed.
